import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#45474c",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001a42",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#bec6e0",
        "secondary": "#565e74",
        "on-tertiary-container": "#4c8dff",
        "on-tertiary-fixed-variant": "#004395",
        "surface-tint": "#545f73",
        "on-secondary-fixed": "#131b2e",
        "outline": "#75777d",
        "primary-fixed": "#d8e3fb",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#adc6ff",
        "primary-fixed-dim": "#bcc7de",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "primary-container": "#1e293b",
        "surface-container": "#e5eeff",
        "secondary-container": "#dae2fd",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#d8e2ff",
        "on-primary-container": "#8590a6",
        "inverse-primary": "#bcc7de",
        "tertiary": "#001334",
        "secondary-fixed": "#dae2fd",
        "on-primary": "#ffffff",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#00275b",
        "primary": "#091426",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-fixed-variant": "#3c475a",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#111c2d",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-background": "#0b1c30",
        "outline-variant": "#c5c6cd",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "margin-mobile": "16px",
        "gutter-mobile": "12px",
        "sm": "8px",
        "lg": "24px",
        "margin-desktop": "24px",
        "gutter-desktop": "16px",
        "base": "4px",
        "md": "16px",
        "xs": "4px"
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "mono-md": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "body-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md-mobile": ["var(--font-inter)", "sans-serif"],
        heading: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "mono-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "body-lg-mobile": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md-mobile": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" }]
      },
    },
  },
  plugins: [],
};

export default config;
