"use client";

import React, { useState, useMemo } from "react";
import {
  useReactTable,
  getCoreRowModel,
  getSortedRowModel,
  getPaginationRowModel,
  flexRender,
  type ColumnDef,
  type SortingState,
} from "@tanstack/react-table";
import {
  FileText,
  Download,
  Search,
  Share2,
  Archive,
  User,
  Clock,
  ExternalLink,
} from "lucide-react";
import type { ReportArchiveItem } from "./types";
import { TablePagination } from "@/components/ui/TablePagination";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";

interface ReportArchiveTableProps {
  initialData?: ReportArchiveItem[];
  onDownloadReport: (item: ReportArchiveItem) => void;
  onShareReport: (item: ReportArchiveItem) => void;
  onPreviewReport: (item: ReportArchiveItem) => void;
}

export function ReportArchiveTable({
  initialData,
  onDownloadReport,
  onShareReport,
  onPreviewReport,
}: ReportArchiveTableProps) {
  const [archive] = useState<ReportArchiveItem[]>(initialData || []);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedFormat, setSelectedFormat] = useState<string>("ALL");
  const [selectedCategory, setSelectedCategory] = useState<string>("ALL");
  const [sorting, setSorting] = useState<SortingState>([
    { id: "generatedAt", desc: true },
  ]);

  const columns = useMemo<ColumnDef<ReportArchiveItem>[]>(
    () => [
      {
        accessorKey: "reportName",
        header: "Report Document",
        cell: ({ row }) => {
          const item = row.original;
          return (
            <div className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-primary font-mono font-bold text-[11px] shrink-0 border border-blue-100">
                {item.format}
              </div>
              <div>
                <span className="font-heading font-bold text-text-primary block text-sm">
                  {item.reportName}
                </span>
                <span className="font-mono text-[11px] text-text-secondary">
                  {item.fileSizeFormatted}
                </span>
              </div>
            </div>
          );
        },
      },
      {
        accessorKey: "category",
        header: "Category",
        cell: ({ row }) => {
          const cat = row.original.category;
          return (
            <Badge
              size="sm"
              variant={
                cat === "Financial"
                  ? "success"
                  : cat === "Settlement"
                  ? "primary"
                  : "neutral"
              }
            >
              {cat}
            </Badge>
          );
        },
      },
      {
        accessorKey: "dateRangeCovered",
        header: "Period Covered",
        cell: ({ row }) => (
          <span className="font-mono text-text-secondary text-xs">
            {row.original.dateRangeCovered}
          </span>
        ),
      },
      {
        id: "generatedBy",
        header: "Generated By",
        cell: ({ row }) => (
          <div className="flex items-center gap-1.5 text-text-primary text-xs">
            <User size={13} className="text-slate-400" />
            <span>{row.original.generatedBy.name}</span>
          </div>
        ),
      },
      {
        accessorKey: "generatedAt",
        header: "Timestamp",
        cell: ({ row }) => (
          <span className="font-mono text-text-secondary text-xs">
            {row.original.generatedAt}
          </span>
        ),
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => {
          const item = row.original;
          return (
            <div className="flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => onPreviewReport(item)}
                title="Preview PDF"
                className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border bg-surface px-3 font-label text-label font-bold text-brand-navy hover:bg-background transition-colors focus:outline-none focus:ring-2 focus:ring-brand-navy"
              >
                <ExternalLink size={14} />
                <span>View</span>
              </button>
              <button
                type="button"
                onClick={() => onShareReport(item)}
                title="Share Link"
                className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-outline-variant/40 bg-surface-white px-2.5 font-label text-label font-bold text-text-grey hover:text-on-surface hover:bg-surface-light-grey transition-colors focus:outline-none"
              >
                <Share2 size={14} />
              </button>
              <button
                type="button"
                onClick={() => onDownloadReport(item)}
                title="Download Document"
                className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-brand-navy px-3 font-label text-label font-bold text-surface-white hover:bg-brand-navy/90 transition-colors focus:outline-none focus:ring-2 focus:ring-brand-navy"
              >
                <Download size={14} />
              </button>
            </div>
          );
        },
      },
    ],
    [onDownloadReport, onPreviewReport, onShareReport]
  );

  const filteredData = useMemo(() => {
    return archive.filter((item) => {
      const matchesSearch =
        searchTerm.trim().length === 0 ||
        item.reportName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        item.generatedBy.name.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesFormat =
        selectedFormat === "ALL" || item.format === selectedFormat;
      const matchesCategory =
        selectedCategory === "ALL" || item.category === selectedCategory;
      return matchesSearch && matchesFormat && matchesCategory;
    });
  }, [archive, searchTerm, selectedFormat, selectedCategory]);

  const table = useReactTable({
    data: filteredData,
    columns,
    state: {
      sorting,
    },
    onSortingChange: setSorting,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    initialState: {
      pagination: {
        pageSize: 5,
      },
    },
  });

  return (
    <div className="rounded-2xl border border-border bg-surface p-5 shadow-sm space-y-4">
      {/* ── Header & Filter Controls ────────────────────────── */}
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between border-b border-border pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="font-heading text-lg font-bold text-text-primary flex items-center gap-2">
              <Archive size={18} className="text-primary" />
              Generated Report Archive &amp; Audit Log
            </h3>
            <Badge size="sm" variant="neutral">
              IMMUTABLE STORE
            </Badge>
          </div>
          <p className="mt-0.5 font-body text-xs text-text-secondary">
            Permanent archive of all system-generated and scheduled financial and operational audit artifacts.
          </p>
        </div>

        {/* Filters Toolbar */}
        <div className="flex flex-wrap items-center gap-2.5">
          <div className="relative min-w-[200px]">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search Report or Author..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="h-9 w-full rounded-xl border border-border bg-surface pl-9 pr-3 font-body text-xs text-text-primary placeholder:text-text-secondary focus:border-primary focus:outline-none"
            />
          </div>

          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="h-9 rounded-xl border border-border bg-surface px-3 font-body text-xs text-text-primary focus:border-primary focus:outline-none"
          >
            <option value="ALL">All Categories</option>
            <option value="Financial">Financial</option>
            <option value="Settlement">Settlement</option>
            <option value="Operations">Operations</option>
            <option value="Inventory">Inventory</option>
          </select>

          <select
            value={selectedFormat}
            onChange={(e) => setSelectedFormat(e.target.value)}
            className="h-9 rounded-xl border border-border bg-surface px-3 font-body text-xs text-text-primary focus:border-primary focus:outline-none"
          >
            <option value="ALL">All Formats</option>
            <option value="PDF">PDF Only</option>
            <option value="CSV">CSV Only</option>
            <option value="XLSX">XLSX Only</option>
          </select>
        </div>
      </div>

      {/* ── TanStack Table Container ────────────────────────── */}
      <div className="overflow-x-auto rounded-xl border border-border bg-surface">
        <table className="w-full text-left border-collapse">
          <thead>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id} className="border-b border-border bg-[#F4F6FB]">
                {headerGroup.headers.map((header) => (
                  <th
                    key={header.id}
                    className="px-4 py-3 font-heading text-xs font-bold uppercase tracking-wider text-slate-700 select-none cursor-pointer"
                    onClick={header.column.getToggleSortingHandler()}
                  >
                    <div className="flex items-center gap-1.5">
                      {flexRender(
                        header.column.columnDef.header,
                        header.getContext()
                      )}
                      {{
                        asc: " ↑",
                        desc: " ↓",
                      }[header.column.getIsSorted() as string] ?? null}
                    </div>
                  </th>
                ))}
              </tr>
            ))}
          </thead>
          <tbody className="divide-y divide-border/60">
            {table.getRowModel().rows.length === 0 ? (
              <tr>
                <td
                  colSpan={columns.length}
                  className="px-4 py-8 text-center font-body text-xs text-text-secondary"
                >
                  No archived reports match your query.
                </td>
              </tr>
            ) : (
              table.getRowModel().rows.map((row) => (
                <tr
                  key={row.id}
                  className="hover:bg-slate-50 transition-colors"
                >
                  {row.getVisibleCells().map((cell) => (
                    <td key={cell.id} className="px-4 py-3 align-middle">
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext()
                      )}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>

        {filteredData.length > 0 && (
          <div className="p-3 border-t border-border">
            <TablePagination
              pageIndex={table.getState().pagination.pageIndex}
              pageSize={table.getState().pagination.pageSize}
              pageCount={table.getPageCount()}
              totalCount={filteredData.length}
              canPreviousPage={table.getCanPreviousPage()}
              canNextPage={table.getCanNextPage()}
              onPageChange={(p) => table.setPageIndex(p)}
              onPageSizeChange={(newSize) => table.setPageSize(newSize)}
            />
          </div>
        )}
      </div>
    </div>
  );
}
