"use client";

import React, { useState } from "react";
import {
  FileText,
  DollarSign,
  TrendingUp,
  Activity,
  Layers,
  Archive,
  Sparkles,
  CheckCircle2,
  Download,
  Flame,
} from "lucide-react";
import type {
  DateHorizon,
  FacilityZone,
  FlowSegment,
  VmiBillingRow,
  ReportArchiveItem,
  PreBuiltTemplate,
  ReportFormat,
  ReportCategory,
} from "./types";
import { ReportsHeader } from "./ReportsHeader";
import { ReportKpis } from "./ReportKpis";
import { VmiBillingTable } from "./VmiBillingTable";
import { TradingMarginSection } from "./TradingMarginSection";
import { ThroughputSection } from "./ThroughputSection";
import { DeliveryPerformanceReport } from "./DeliveryPerformanceReport";
import { MonthlyHeatmap } from "@/components/dashboard/MonthlyHeatmap";
import { TemplateCardGrid } from "./TemplateCardGrid";
import { ReportArchiveTable } from "./ReportArchiveTable";
import { PdfPreviewModal } from "./PdfPreviewModal";
import { CustomReportBuilderModal } from "./CustomReportBuilderModal";

export function WarehouseReportsHub() {
  const [facility, setFacility] = useState<FacilityZone>("all");
  const [horizon, setHorizon] = useState<DateHorizon>("30D");
  const [startDate, setStartDate] = useState("2026-08-01");
  const [endDate, setEndDate] = useState("2026-08-31");
  const [activeSection, setActiveSection] = useState<"all" | "financial" | "operations" | "heatmap" | "archive">("all");

  // Modal States
  const [isPdfPreviewOpen, setIsPdfPreviewOpen] = useState(false);
  const [pdfModalTitle, setPdfModalTitle] = useState("Master Stock Position & Financial Valuation Summary");
  const [pdfModalSubtitle, setPdfModalSubtitle] = useState("Official Consolidated WMS Balance Sheet & CBM Space Reconciliation");
  const [pdfModalRef, setPdfModalRef] = useState("DS-RPT-2026-0831-VAL");

  const [isBuilderOpen, setIsBuilderOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage(null);
    }, 4000);
  };

  // Quick PDF Generator
  const handleQuickGeneratePdf = () => {
    setPdfModalTitle("Consolidated Warehouse Valuation & Inventory Position");
    setPdfModalSubtitle("Executive overview of all 1,420 lots across VMI and Trading accounts");
    setPdfModalRef("DS-RPT-VAL-MTD");
    setIsPdfPreviewOpen(true);
  };

  // VMI Billing Row PDF
  const handleGenerateInvoicePdf = (row: VmiBillingRow) => {
    setPdfModalTitle(`Statement of Account — ${row.clientName}`);
    setPdfModalSubtitle(`CBM Storage & Consignment Handling for Period Ending Aug 31, 2026 (${row.unbilledDays} Unbilled Days)`);
    setPdfModalRef(`SOA-${row.clientCode}-202608`);
    setIsPdfPreviewOpen(true);
  };

  const handleAuditDwellTime = (row: VmiBillingRow) => {
    showToast(`Opening Dwell Time Audit logs for ${row.clientName} (${row.occupiedCbm} m³ consumed).`);
  };

  const handleRunTemplate = (template: PreBuiltTemplate, format: ReportFormat) => {
    if (format === "PDF") {
      setPdfModalTitle(template.title);
      setPdfModalSubtitle(template.description);
      setPdfModalRef(`DS-TPL-${template.id.toUpperCase()}`);
      setIsPdfPreviewOpen(true);
    } else {
      showToast(`Generating ${template.title} (.${format})... Export will download shortly.`);
    }
  };

  const handleScheduleTemplate = (template: PreBuiltTemplate) => {
    showToast(`Automated schedule confirmed for "${template.title}": ${template.scheduleFrequency}.`);
  };

  const handleDownloadReport = (item: ReportArchiveItem) => {
    showToast(`Downloading archived report: ${item.reportName}`);
  };

  const handleShareReport = (item: ReportArchiveItem) => {
    showToast(`Shareable secure link generated for ${item.reportName}. Copied to clipboard.`);
  };

  const handlePreviewReport = (item: ReportArchiveItem) => {
    setPdfModalTitle(item.reportName.replace(".pdf", ""));
    setPdfModalSubtitle(`Archived ${item.category} Report · Generated by ${item.generatedBy.name}`);
    setPdfModalRef(`ARC-${item.id.toUpperCase()}`);
    setIsPdfPreviewOpen(true);
  };

  const handleExportRawData = (format: "csv" | "xlsx") => {
    showToast(`Exporting raw warehouse transaction ledger (.${format.toUpperCase()})...`);
  };

  const handleCustomBuildComplete = (config: {
    title: string;
    category: ReportCategory;
    format: ReportFormat;
    metrics: string[];
    dimensions: string[];
  }) => {
    showToast(`Custom report "${config.title}" generated successfully with ${config.metrics.length} metrics.`);
    if (config.format === "PDF") {
      setPdfModalTitle(config.title);
      setPdfModalSubtitle(`Custom ${config.category} Query · ${config.dimensions.join(", ")}`);
      setPdfModalRef(`DS-CUST-${Date.now().toString().slice(-6)}`);
      setIsPdfPreviewOpen(true);
    }
  };

  return (
    <div className="space-y-6">
      {/* ── 1. Global Header & Control Toolbar ────────────────────────────── */}
      <ReportsHeader
        facility={facility}
        horizon={horizon}
        startDate={startDate}
        endDate={endDate}
        onFacilityChange={setFacility}
        onHorizonChange={setHorizon}
        onStartDateChange={setStartDate}
        onEndDateChange={setEndDate}
        onOpenReportBuilder={() => setIsBuilderOpen(true)}
        onQuickGeneratePdf={handleQuickGeneratePdf}
        onExportRawData={handleExportRawData}
      />

      {/* Toast Notification */}
      {toastMessage && (
        <div className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-900 shadow-sm animate-in fade-in slide-in-from-top-2">
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-600 shrink-0" />
            <span>{toastMessage}</span>
          </div>
          <button
            type="button"
            onClick={() => setToastMessage(null)}
            className="text-emerald-700 hover:text-emerald-950 font-mono text-[11px] underline"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* ── 2. Executive Reporting & Settlement KPIs (Bento Row) ───────────── */}
      <ReportKpis />

      {/* ── Section Quick Navigation Filter Bar ───────────────────────────── */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200/80 pb-2">
        <div className="flex flex-wrap items-center gap-1.5 font-label text-xs font-semibold">
          <button
            type="button"
            onClick={() => setActiveSection("all")}
            className={`rounded-xl px-3.5 py-1.5 transition-all ${
              activeSection === "all"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            All Reports &amp; Analytics
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("financial")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "financial"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <DollarSign size={13} />
            <span>Financial Settlement &amp; Margins</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("operations")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "operations"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Activity size={13} />
            <span>Throughput &amp; OTIF SLA</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("heatmap")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "heatmap"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Flame size={13} />
            <span>Location Heatmap</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("archive")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "archive"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Archive size={13} />
            <span>Report Archive &amp; Templates</span>
          </button>
        </div>
      </div>

      {/* ── 3. Dedicated Financial Settlement & Margin Reports ─────────────── */}
      {(activeSection === "all" || activeSection === "financial") && (
        <section className="space-y-6 animate-in fade-in">
          {/* A. VMI Client Storage & CBM Billing Reconciliation */}
          <VmiBillingTable
            onGenerateInvoicePdf={handleGenerateInvoicePdf}
            onAuditDwellTime={handleAuditDwellTime}
          />

          {/* B & C. Trading Revenue, COGS, Margin Realization & Product Line Margin Table */}
          <TradingMarginSection />
        </section>
      )}

      {/* ── 4. Throughput, Delivery & Storage Reports ──────────────────────── */}
      {(activeSection === "all" || activeSection === "operations") && (
        <section className="space-y-6 animate-in fade-in">
          {/* A & C. Movement Volume Throughput & Location Occupancy */}
          <ThroughputSection />

          {/* B. Delivery SLA & OTIF Fulfillment Report */}
          <DeliveryPerformanceReport />
        </section>
      )}

      {/* ── 5. Monthly Location Intelligence Heatmap (31-Day View) ────────── */}
      {(activeSection === "all" || activeSection === "heatmap") && (
        <section className="animate-in fade-in">
          <MonthlyHeatmap />
        </section>
      )}

      {/* ── 6 & 7. Templates Grid & Reports Archive Log ───────────────────── */}
      {(activeSection === "all" || activeSection === "archive") && (
        <section className="space-y-6 animate-in fade-in">
          {/* Pre-built Templates Grid */}
          <TemplateCardGrid
            onRunTemplate={handleRunTemplate}
            onScheduleTemplate={handleScheduleTemplate}
          />

          {/* Generated Reports Archive */}
          <ReportArchiveTable
            onDownloadReport={handleDownloadReport}
            onShareReport={handleShareReport}
            onPreviewReport={handlePreviewReport}
          />
        </section>
      )}

      {/* ── 8. Live In-Browser PDF Preview Dialog ─────────────────────────── */}
      <PdfPreviewModal
        isOpen={isPdfPreviewOpen}
        onClose={() => setIsPdfPreviewOpen(false)}
        reportTitle={pdfModalTitle}
        reportSubtitle={pdfModalSubtitle}
        reportRefNumber={pdfModalRef}
      />

      {/* ── 9. Interactive Custom Report Builder Modal ────────────────────── */}
      <CustomReportBuilderModal
        isOpen={isBuilderOpen}
        onClose={() => setIsBuilderOpen(false)}
        onBuildComplete={handleCustomBuildComplete}
      />
    </div>
  );
}
