"use client";

import React, { useState } from "react";
import {
  DollarSign,
  Activity,
  Archive,
  CheckCircle2,
  AlertCircle,
  Flame,
} from "lucide-react";
import type {
  DateHorizon,
  FacilityZone,
  VmiBillingRow,
  ReportArchiveItem,
  PreBuiltTemplate,
  ReportFormat,
  ReportCategory,
  TradingMarginRow,
  TradingCategoryPerformance,
  MovementThroughputDatum,
  DeliverySlaDatum,
} from "./types";
import { ReportsHeader } from "./ReportsHeader";
import { ReportKpis, type ReportKpisProps } from "./ReportKpis";
import { VmiBillingTable } from "./VmiBillingTable";
import { TradingMarginSection } from "./TradingMarginSection";
import { ThroughputSection } from "./ThroughputSection";
import { DeliveryPerformanceReport } from "./DeliveryPerformanceReport";
import { MonthlyHeatmap } from "@/components/dashboard/MonthlyHeatmap";
import { TemplateCardGrid } from "./TemplateCardGrid";
import { ReportArchiveTable } from "./ReportArchiveTable";
import { PdfPreviewModal } from "./PdfPreviewModal";
import { CustomReportBuilderModal } from "./CustomReportBuilderModal";
import { exportRawTransactionsCsvAction, generateCustomReportAction } from "@/lib/actions/reports";

export interface WarehouseReportsHubProps {
  kpis?: ReportKpisProps["kpis"];
  vmiBillingRows?: VmiBillingRow[];
  tradingMargin?: {
    marginHistory: TradingMarginRow[];
    categoryBreakdown: TradingCategoryPerformance[];
  };
  throughput?: MovementThroughputDatum[];
  deliverySla?: DeliverySlaDatum[];
  archiveItems?: ReportArchiveItem[];
  canReadFinancial?: boolean;
}

export function WarehouseReportsHub({
  kpis,
  vmiBillingRows,
  tradingMargin,
  throughput,
  deliverySla,
  archiveItems,
  canReadFinancial = true,
}: WarehouseReportsHubProps) {
  const [facility, setFacility] = useState<FacilityZone>("all");
  const [horizon, setHorizon] = useState<DateHorizon>("30D");
  const [startDate, setStartDate] = useState("2026-08-01");
  const [endDate, setEndDate] = useState("2026-08-31");
  const [activeSection, setActiveSection] = useState<"all" | "financial" | "operations" | "heatmap" | "archive">("all");

  // Modal States
  const [isPdfPreviewOpen, setIsPdfPreviewOpen] = useState(false);
  const [pdfModalTitle, setPdfModalTitle] = useState("Master Stock Position & Financial Valuation Summary");
  const [pdfModalSubtitle, setPdfModalSubtitle] = useState("Official Consolidated WMS Balance Sheet & CBM Space Reconciliation");
  const [pdfModalRef, setPdfModalRef] = useState("DS-RPT-2026-0831-VAL");

  const [isBuilderOpen, setIsBuilderOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setErrorMessage(null);
    setTimeout(() => {
      setToastMessage(null);
    }, 4500);
  };

  const showError = (msg: string) => {
    setErrorMessage(msg);
    setToastMessage(null);
    setTimeout(() => {
      setErrorMessage(null);
    }, 4500);
  };

  // Quick PDF Generator
  const handleQuickGeneratePdf = () => {
    setPdfModalTitle("Consolidated Warehouse Valuation & Inventory Position");
    setPdfModalSubtitle("Executive overview of all active lots across VMI and Trading accounts");
    setPdfModalRef("DS-RPT-VAL-MTD");
    setIsPdfPreviewOpen(true);
  };

  // VMI Billing Row PDF
  const handleGenerateInvoicePdf = (row: VmiBillingRow) => {
    setPdfModalTitle(`Statement of Account — ${row.clientName}`);
    setPdfModalSubtitle(`CBM Storage & Consignment Handling for Period (${row.unbilledDays} Unbilled Days)`);
    setPdfModalRef(`SOA-${row.clientCode}-202608`);
    setIsPdfPreviewOpen(true);
  };

  const handleAuditDwellTime = (row: VmiBillingRow) => {
    showToast(`Dwell Time Audit opened for ${row.clientName} (${row.occupiedCbm} m³ consumed).`);
  };

  const handleRunTemplate = (template: PreBuiltTemplate, format: ReportFormat) => {
    if (format === "PDF") {
      setPdfModalTitle(template.title);
      setPdfModalSubtitle(template.description);
      setPdfModalRef(`DS-TPL-${template.id.toUpperCase()}`);
      setIsPdfPreviewOpen(true);
    } else {
      showToast(`Generating ${template.title} (.${format})... Export prepared.`);
    }
  };

  const handleScheduleTemplate = (template: PreBuiltTemplate) => {
    showToast(`Automated schedule confirmed for "${template.title}": ${template.scheduleFrequency}.`);
  };

  const handleDownloadReport = (item: ReportArchiveItem) => {
    showToast(`Downloading archived report: ${item.reportName}`);
  };

  const handleShareReport = (item: ReportArchiveItem) => {
    showToast(`Shareable secure link generated for ${item.reportName}. Copied to clipboard.`);
  };

  const handlePreviewReport = (item: ReportArchiveItem) => {
    setPdfModalTitle(item.reportName.replace(".pdf", ""));
    setPdfModalSubtitle(`Archived ${item.category} Report · Generated by ${item.generatedBy.name}`);
    setPdfModalRef(`ARC-${item.id.toUpperCase()}`);
    setIsPdfPreviewOpen(true);
  };

  // Live Raw Ledger Export Action
  const handleExportRawData = async (format: "csv" | "xlsx") => {
    try {
      const res = await exportRawTransactionsCsvAction(format);
      if (res.success && res.csvContent) {
        // Trigger client download of genuine database transactions
        const blob = new Blob([res.csvContent], { type: "text/csv;charset=utf-8;" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.setAttribute("href", url);
        link.setAttribute("download", res.filename || "dyna-serv-ledger.csv");
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        showToast(res.message);
      } else {
        showError(res.message || "Failed to export raw transactions.");
      }
    } catch (err) {
      console.error(err);
      showError("Error exporting raw transaction data.");
    }
  };

  const handleCustomBuildComplete = async (config: {
    title: string;
    category: ReportCategory;
    format: ReportFormat;
    metrics: string[];
    dimensions: string[];
  }) => {
    try {
      const res = await generateCustomReportAction(config);
      if (res.success) {
        showToast(res.message);
        if (config.format === "PDF") {
          setPdfModalTitle(config.title);
          setPdfModalSubtitle(`Custom ${config.category} Query · ${config.dimensions.join(", ")}`);
          setPdfModalRef(`DS-CUST-${Date.now().toString().slice(-6)}`);
          setIsPdfPreviewOpen(true);
        }
      } else {
        showError(res.message);
      }
    } catch (err) {
      console.error(err);
      showError("Failed to build custom report.");
    }
  };

  return (
    <div className="space-y-6">
      {/* ── 1. Global Header & Control Toolbar ────────────────────────────── */}
      <ReportsHeader
        facility={facility}
        horizon={horizon}
        startDate={startDate}
        endDate={endDate}
        onFacilityChange={setFacility}
        onHorizonChange={setHorizon}
        onStartDateChange={setStartDate}
        onEndDateChange={setEndDate}
        onOpenReportBuilder={() => setIsBuilderOpen(true)}
        onQuickGeneratePdf={handleQuickGeneratePdf}
        onExportRawData={handleExportRawData}
      />

      {/* Toast Notification */}
      {toastMessage && (
        <div className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-900 shadow-sm animate-in fade-in slide-in-from-top-2">
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-600 shrink-0" />
            <span>{toastMessage}</span>
          </div>
          <button
            type="button"
            onClick={() => setToastMessage(null)}
            className="text-emerald-700 hover:text-emerald-950 font-mono text-[11px] underline"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Error Toast */}
      {errorMessage && (
        <div className="flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-xs font-bold text-rose-900 shadow-sm animate-in fade-in slide-in-from-top-2">
          <div className="flex items-center gap-2">
            <AlertCircle size={16} className="text-rose-600 shrink-0" />
            <span>{errorMessage}</span>
          </div>
          <button
            type="button"
            onClick={() => setErrorMessage(null)}
            className="text-rose-700 hover:text-rose-950 font-mono text-[11px] underline"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* ── 2. Executive Reporting & Settlement KPIs (Bento Row) ───────────── */}
      <ReportKpis kpis={kpis} />

      {/* ── Section Quick Navigation Filter Bar ───────────────────────────── */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200/80 pb-2">
        <div className="flex flex-wrap items-center gap-1.5 font-label text-xs font-semibold">
          <button
            type="button"
            onClick={() => setActiveSection("all")}
            className={`rounded-xl px-3.5 py-1.5 transition-all ${
              activeSection === "all"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            All Reports &amp; Analytics
          </button>

          {canReadFinancial && (
            <button
              type="button"
              onClick={() => setActiveSection("financial")}
              className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
                activeSection === "financial"
                  ? "bg-brand-navy text-white font-bold shadow-2xs"
                  : "text-slate-600 hover:text-slate-900 bg-slate-100"
              }`}
            >
              <DollarSign size={13} />
              <span>Financial Settlement &amp; Margins</span>
            </button>
          )}

          <button
            type="button"
            onClick={() => setActiveSection("operations")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "operations"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Activity size={13} />
            <span>Throughput &amp; OTIF SLA</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("heatmap")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "heatmap"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Flame size={13} />
            <span>Location Heatmap</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("archive")}
            className={`rounded-xl px-3.5 py-1.5 transition-all flex items-center gap-1.5 ${
              activeSection === "archive"
                ? "bg-brand-navy text-white font-bold shadow-2xs"
                : "text-slate-600 hover:text-slate-900 bg-slate-100"
            }`}
          >
            <Archive size={13} />
            <span>Report Archive &amp; Templates</span>
          </button>
        </div>
      </div>

      {/* ── 3. Dedicated Financial Settlement & Margin Reports ─────────────── */}
      {canReadFinancial && (activeSection === "all" || activeSection === "financial") && (
        <section className="space-y-6 animate-in fade-in">
          {/* A. VMI Client Storage & CBM Billing Reconciliation */}
          <VmiBillingTable
            initialData={vmiBillingRows}
            onGenerateInvoicePdf={handleGenerateInvoicePdf}
            onAuditDwellTime={handleAuditDwellTime}
          />

          {/* B & C. Trading Revenue, COGS, Margin Realization & Product Line Margin Table */}
          <TradingMarginSection initialData={tradingMargin} />
        </section>
      )}

      {/* ── 4. Throughput, Delivery & Storage Reports ──────────────────────── */}
      {(activeSection === "all" || activeSection === "operations") && (
        <section className="space-y-6 animate-in fade-in">
          {/* A & C. Movement Volume Throughput & Location Occupancy */}
          <ThroughputSection initialData={throughput} />

          {/* B. Delivery SLA & OTIF Fulfillment Report */}
          <DeliveryPerformanceReport initialData={deliverySla} />
        </section>
      )}

      {/* ── 5. Monthly Location Intelligence Heatmap (31-Day View) ────────── */}
      {(activeSection === "all" || activeSection === "heatmap") && (
        <section className="animate-in fade-in">
          <MonthlyHeatmap />
        </section>
      )}

      {/* ── 6 & 7. Templates Grid & Reports Archive Log ───────────────────── */}
      {(activeSection === "all" || activeSection === "archive") && (
        <section className="space-y-6 animate-in fade-in">
          {/* Pre-built Templates Grid */}
          <TemplateCardGrid
            onRunTemplate={handleRunTemplate}
            onScheduleTemplate={handleScheduleTemplate}
          />

          {/* Generated Reports Archive */}
          <ReportArchiveTable
            initialData={archiveItems}
            onDownloadReport={handleDownloadReport}
            onShareReport={handleShareReport}
            onPreviewReport={handlePreviewReport}
          />
        </section>
      )}

      {/* ── 8. Live In-Browser PDF Preview Dialog ─────────────────────────── */}
      <PdfPreviewModal
        isOpen={isPdfPreviewOpen}
        onClose={() => setIsPdfPreviewOpen(false)}
        reportTitle={pdfModalTitle}
        reportSubtitle={pdfModalSubtitle}
        reportRefNumber={pdfModalRef}
      />

      {/* ── 9. Interactive Custom Report Builder Modal ────────────────────── */}
      <CustomReportBuilderModal
        isOpen={isBuilderOpen}
        onClose={() => setIsBuilderOpen(false)}
        onBuildComplete={handleCustomBuildComplete}
      />
    </div>
  );
}
