"use client";

import React, { useState, useMemo } from "react";
import {
  FileText,
  Download,
  Share2,
  Archive,
  User,
  ExternalLink,
  Eye,
  ShieldCheck,
} from "lucide-react";
import type { ReportArchiveRow } from "@/lib/db/queries/documents";
import { TablePagination } from "@/components/ui/TablePagination";
import { PdfPreviewModal } from "@/components/reports/PdfPreviewModal";

interface ReportDocumentsTableProps {
  rows: ReportArchiveRow[];
}

const CATEGORY_BADGES: Record<string, string> = {
  Financial: "bg-emerald-50 text-emerald-800 border border-emerald-200",
  Settlement: "bg-blue-50 text-brand-navy border border-blue-200",
  Operations: "bg-slate-100 text-slate-800 border border-slate-200",
  Inventory: "bg-purple-50 text-purple-800 border border-purple-200",
};

export function ReportDocumentsTable({ rows }: ReportDocumentsTableProps) {
  const [selectedReport, setSelectedReport] = useState<ReportArchiveRow | null>(null);
  const [pageIndex, setPageIndex] = useState(0);
  const [pageSize, setPageSize] = useState(10);

  const totalCount = rows.length;
  const pageCount = Math.ceil(totalCount / pageSize) || 1;
  const pagedRows = useMemo(() => {
    return rows.slice(pageIndex * pageSize, (pageIndex + 1) * pageSize);
  }, [rows, pageIndex, pageSize]);

  const handleShare = (row: ReportArchiveRow) => {
    if (typeof window !== "undefined") {
      navigator.clipboard?.writeText?.(window.location.origin + `/documents?tab=reports&docId=${row.id}`);
      alert(`Secure link for "${row.reportName}" copied to clipboard.`);
    }
  };

  const handleDownload = (row: ReportArchiveRow) => {
    // Generate text/csv or trigger download
    const csvContent = "data:text/csv;charset=utf-8," +
      `"Report Name","Document Number","Category","Period","Generated By","Timestamp"\n` +
      `"${row.reportName}","${row.documentNumber}","${row.category}","${row.dateRangeCovered}","${row.generatedByName}","${row.createdAt}"`;
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", row.reportName);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (rows.length === 0) {
    return (
      <div className="flex flex-col items-center gap-3 rounded-2xl border border-outline-variant/30 bg-surface-white px-6 py-12 text-center shadow-elevation-1">
        <Archive size={40} className="text-text-grey" aria-hidden="true" />
        <h3 className="font-heading text-headline-sm font-bold text-on-surface">No Archived Reports Found</h3>
        <p className="font-body text-body-md text-text-grey">
          All generated audit reports, statements, and operational snapshots will be preserved here permanently.
        </p>
      </div>
    );
  }

  return (
    <>
      <div className="overflow-hidden rounded-2xl border border-outline-variant/30 bg-surface-white shadow-elevation-1">
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b border-outline-variant/30 bg-surface-light-grey">
                <th className="px-4 py-3 text-left font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Report Document
                </th>
                <th className="px-4 py-3 text-left font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Category
                </th>
                <th className="px-4 py-3 text-left font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Period Covered
                </th>
                <th className="px-4 py-3 text-left font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Generated By
                </th>
                <th className="px-4 py-3 text-left font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Timestamp
                </th>
                <th className="px-4 py-3 text-right font-label text-label uppercase tracking-[0.05em] text-text-grey">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-outline-variant/20">
              {pagedRows.map((r) => {
                const categoryClass = CATEGORY_BADGES[r.category] ?? "bg-slate-100 text-slate-700";
                const formattedDate = new Date(r.createdAt).toISOString().replace("T", " ").slice(0, 16);

                return (
                  <tr key={r.id} className="hover:bg-surface-light-grey/40 transition-colors">
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2.5">
                        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-navy/10 text-brand-navy font-mono font-bold text-[11px] shrink-0 border border-brand-navy/20">
                          {r.format}
                        </div>
                        <div>
                          <span className="font-heading font-bold text-on-surface block text-body-sm">
                            {r.reportName}
                          </span>
                          <span className="font-mono text-[11px] text-text-grey">
                            {r.fileSizeFormatted}
                          </span>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-3">
                      <span className={`inline-flex rounded-full px-2.5 py-0.5 font-label text-[11px] font-bold uppercase tracking-wider ${categoryClass}`}>
                        {r.category}
                      </span>
                    </td>
                    <td className="px-4 py-3 font-mono text-mono-sm text-text-grey">
                      {r.dateRangeCovered}
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1.5 font-body text-body-sm text-on-surface">
                        <User size={13} className="text-text-grey" />
                        <span>{r.generatedByName}</span>
                      </div>
                    </td>
                    <td className="px-4 py-3 font-mono text-mono-sm text-text-grey">
                      {formattedDate}
                    </td>
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          type="button"
                          onClick={() => setSelectedReport(r)}
                          title="Preview PDF"
                          className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-border bg-surface px-3 font-label text-label font-bold text-brand-navy hover:bg-background transition-colors focus:outline-none focus:ring-2 focus:ring-brand-navy"
                        >
                          <Eye size={14} />
                          <span>Preview PDF</span>
                        </button>
                        <button
                          type="button"
                          onClick={() => handleShare(r)}
                          title="Share Link"
                          className="inline-flex h-9 items-center gap-1.5 rounded-lg border border-outline-variant/40 bg-surface-white px-2.5 font-label text-label font-bold text-text-grey hover:text-on-surface hover:bg-surface-light-grey transition-colors focus:outline-none"
                        >
                          <Share2 size={14} />
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownload(r)}
                          title="Download Document"
                          className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-brand-navy px-3 font-label text-label font-bold text-surface-white hover:bg-brand-navy/90 transition-colors focus:outline-none focus:ring-2 focus:ring-brand-navy"
                        >
                          <Download size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        <TablePagination
          pageIndex={pageIndex}
          pageSize={pageSize}
          totalCount={totalCount}
          pageCount={pageCount}
          canPreviousPage={pageIndex > 0}
          canNextPage={pageIndex < pageCount - 1}
          onPageChange={(newPageIndex) => setPageIndex(newPageIndex)}
          onPageSizeChange={(newPageSize) => {
            setPageSize(newPageSize);
            setPageIndex(0);
          }}
          pageSizeOptions={[5, 10, 20, 50]}
        />
      </div>

      {selectedReport && (
        <PdfPreviewModal
          isOpen={!!selectedReport}
          onClose={() => setSelectedReport(null)}
          reportTitle={selectedReport.reportName.replace(".pdf", "")}
          reportSubtitle={`Archived ${selectedReport.category} Document · Generated by ${selectedReport.generatedByName}`}
          reportRefNumber={selectedReport.documentNumber}
        />
      )}
    </>
  );
}
