import type { StatusToken } from "./types";
import { formatNumber } from "./utils";

const tokenClass: Record<StatusToken, string> = { available: "stroke-status-available", pending: "stroke-status-pending", held: "stroke-status-held", neutral: "stroke-status-neutral", expired: "stroke-brand-royal-blue/50" };
export function DonutChart({ segments, title, centerLabel, centerValue }: { segments: { label: string; value: number; statusToken: StatusToken }[]; title: string; centerLabel?: string; centerValue?: number }) {
  const total = segments.reduce((sum, segment) => sum + segment.value, 0);
  return <section role="img" aria-label={`${title}: ${segments.map((segment) => `${segment.label} ${segment.value}`).join(", ")}`} className="rounded bg-surface-white p-6 shadow-elevation-1">
    <div className="flex flex-wrap items-center gap-6"><div className="relative h-40 w-40"><svg viewBox="0 0 42 42" className="h-full w-full -rotate-90" aria-hidden="true"><circle cx="21" cy="21" r="15.5" fill="none" className="stroke-surface-light-grey" strokeWidth="7" />{segments.map((segment, index) => { const prior = segments.slice(0, index).reduce((sum, item) => sum + item.value, 0); const circumference = 2 * Math.PI * 15.5; return <circle key={segment.label} cx="21" cy="21" r="15.5" fill="none" className={tokenClass[segment.statusToken]} strokeWidth="7" strokeDasharray={`${(segment.value / Math.max(total, 1)) * circumference} ${circumference}`} strokeDashoffset={-(prior / Math.max(total, 1)) * circumference} />; })}</svg><div className="absolute inset-8 flex flex-col items-center justify-center rounded-full bg-surface-white text-center"><span className="font-heading text-data-display font-semibold">{centerValue ?? total}</span>{centerLabel && <span className="font-label text-label text-text-grey">{centerLabel}</span>}</div></div>
      <ul className="space-y-2">{segments.map((segment) => <li key={segment.label} className="flex items-center gap-2 font-label text-label"><span className={`h-3 w-3 rounded-sm ${tokenClass[segment.statusToken]}`} aria-hidden="true" /><span>{segment.label}</span><span className="font-mono text-mono-sm">{formatNumber(segment.value)} ({total ? Math.round(segment.value / total * 100) : 0}%)</span></li>)}</ul></div>
    <table className="sr-only"><caption>{title}</caption><thead><tr><th>Status</th><th>Count</th></tr></thead><tbody>{segments.map((segment) => <tr key={segment.label}><td>{segment.label}</td><td>{segment.value}</td></tr>)}</tbody></table>
  </section>;
}
