"use client";

import type { StockLevelRow } from "./types";
import { formatNumber, statusClass } from "./utils";

const columns = [["lotNumber", "Lot"], ["itemCode", "Item"], ["itemName", "Name"], ["flowType", "Flow"], ["locationLabel", "Location"], ["qtyAvailable", "Available"], ["qtyCommitted", "Committed"], ["qtyRemaining", "Remaining"], ["status", "Status"], ["expiryDate", "Expiry"]] as const;
export function StockLevelTable({ rows, sortKey, sortDirection, onSort, onRowClick }: { rows: StockLevelRow[]; sortKey: string; sortDirection: "asc" | "desc"; onSort: (key: string) => void; onRowClick?: (lotId: string) => void }) {
  return <div className="overflow-x-auto rounded shadow-elevation-1"><table role="table" className="min-w-[900px] w-full border-collapse bg-white"><thead><tr className="bg-primary text-left text-white">{columns.map(([key, label]) => <th key={key} scope="col" aria-sort={sortKey === key ? sortDirection === "asc" ? "ascending" : "descending" : "none"} className="whitespace-nowrap px-4 py-3 font-label text-label font-semibold uppercase tracking-[0.05em]"><button type="button" onClick={() => onSort(key)} className="focus:outline-none focus:ring-2 focus:ring-white">{label} {sortKey === key ? sortDirection === "asc" ? "↑" : "↓" : "↕"}</button></th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.lotNumber}-${row.locationLabel}`} onClick={() => onRowClick?.(row.lotNumber)} className={`${index % 2 ? "bg-surface-dim" : "bg-white"} ${onRowClick ? "cursor-pointer hover:bg-surface-dim" : ""}`}><td className="px-4 py-3 font-mono text-mono-md">{row.lotNumber}</td><td className="px-4 py-3 font-mono text-mono-md">{row.itemCode}</td><td className="px-4 py-3 font-body text-body-md">{row.itemName}</td><td className="px-4 py-3 font-body text-body-md capitalize">{row.flowType}</td><td className="px-4 py-3 font-mono text-mono-md">{row.locationLabel}</td><td className="px-4 py-3 text-right font-mono text-mono-md">{formatNumber(row.qtyAvailable)}</td><td className="px-4 py-3 text-right font-mono text-mono-md">{formatNumber(row.qtyCommitted)}</td><td className="px-4 py-3 text-right font-mono text-mono-md">{formatNumber(row.qtyRemaining)}</td><td className="px-4 py-3"><span aria-label={`Status: ${row.status}`} className={`rounded-full px-2 py-1 font-label text-label font-semibold uppercase ${statusClass(row.status)}`}>{row.status}</span></td><td className={`px-4 py-3 font-mono text-mono-md ${row.expiryDate && new Date(row.expiryDate).getTime() - Date.now() < 30 * 86400000 ? "text-status-error" : ""}`}>{row.expiryDate ?? "—"}</td></tr>)}</tbody></table></div>;
}
